# Generated by Django 2.0.7 on 2018-07-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_name', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='script_name')),
                ('script', models.TextField()),
            ],
        ),
    ]
