# Generated by Django 2.0.5 on 2018-10-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='script',
            fields=[
                ('script_name', models.CharField(db_index=True, max_length=40, primary_key=True, serialize=False, unique=True, verbose_name='Название программы')),
                ('script', models.TextField(verbose_name='Текст программы')),
            ],
        ),
    ]
