# Generated by Django 2.0.5 on 2018-10-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='script',
            name='id',
        ),
        migrations.AlterField(
            model_name='script',
            name='script',
            field=models.TextField(verbose_name='Текст программы'),
        ),
        migrations.AlterField(
            model_name='script',
            name='script_name',
            field=models.CharField(db_index=True, max_length=40, primary_key=True, serialize=False, unique=True, verbose_name='Название программы'),
        ),
    ]
